[package]
name = "wasm_gamelib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"
js-sys = "0.3.59"

spherical_go_game_lib = {path = "../gamelib"}
