//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::games::Entity as Games;
pub use super::histories::Entity as Histories;
pub use super::rooms::Entity as Rooms;
pub use super::users::Entity as Users;
